config/routes.rb
Rails.application.routes.draw do
  root 'static_page#home'
  
  devise_for :users

  resources :hobbies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hobby.rb
class Hobby < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :hobbies

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :set_hobby, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def index
    current_user.hobbies
  end

  def show
  end

  def new
    @hobby = Hobby.new
  end

  def create
    @hobby = current_user.hobbies.new(hobby_params)
    if @hobby.save
      flash[:success] = "#{@hobby.name} Created"
      redirect_to hobbies_path
    else
      flash[:error] = "Error: #{@hobby.errors.full_messages.join("\n")}"
      render :new
    end
  end

  def edit
  end

  def update
    if @hobby.update(hobby_params)
      flash[:success] = "#{@hobby.name} Updated"
      redirect_to hobbies_path
    else
      flash[:error] = "Error: #{@hobby.errors.full_messages.join("\n")}"
      render :edit
    end
  end

  def destroy
    @hobby.destroy
    redirect_to hobbies_path
  end

  private
    def set_hobby
      @hobby = current_user.hobbies.find(params[:id])
    end

    def hobby_params
      params.require(:hobby).permit(:name)
    end

    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/hobbies/_form.html.erb
<%= form_with(model: hobby, local: true) do |f| %>
  <div class= "field">
    <%= f.text_field :name, required: true, autofocus: true, placeholder: "Hobby Name" %>
  </div>
  <div class= "action">
    <%= f.submit "Submit", class: "btn" %>
  </div>
<% end %>

app/views/hobbies/edit.html.erb
<h3>Edit A Hobby</h3>
<hr>

<%= render "form", hobby: @hobby %>
<br>
<%= link_to "Back", hobbies_path%>

app/views/hobbies/index.html.erb
<h1><%= current_user.full_name %>'s Hobbies</h1>
<hr>
<h5> Add your hobbies: <%= link_to "New Hobby", new_hobby_path, class:"btn green"%> </h5>

<ul>
  <% current_user.hobbies.each do |h| %>
    <hr>
    <li><h3><%= h.name %></h3></li>
    <%= link_to "Edit", edit_hobby_path(h), class:"btn deep-purple accent-2" %>
    |
    <%= link_to "Delete", hobby_path(h), method: :delete, class:"btn blue" %>
    <hr>
  <% end %>
</ul>

app/views/hobbies/new.html.erb
<h3>Add A New Hobby</h3>
<hr>

<%= render "form", hobby: @hobby %>
<br>
<%= link_to "Back", hobbies_path%>

app/views/hobbies/show.html.erb
<h1>Hobbies#show</h1>
<p>Find me in app/views/hobbies/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<div class= "nav-wrapper">
<% if current_user %>
  <%= link_to "Home", root_path, class:"btn deep-purple accent-2" %>
  <%= link_to "Hobbies", hobbies_path, class:"btn deep-purple accent-2" %>
  <div class="right">
    Logged In |
    <%= link_to "Edit User", edit_user_registration_path, class: "btn deep-purple accent-2"%>
    <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"btn red"%>
  </div>
<% else %>
  <%= link_to "Home", root_path, class:"btn deep-purple accent-2" %>
  <div class="right">
    <%= link_to 'Sign Up', new_user_registration_path, class: "btn green" %>
    or
    <%= link_to 'Log In', new_user_session_path, class: "btn green" %>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserHobbyList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/navbar" %>
    <div class= "container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/static_page/home.html.erb
<h1>Welcome to the Hobby Lists Home Page</h1>